version: "3"
services:

  # Selenium サーバを起動するコンテナ
  selenium:
    container_name: rfctrans-selenium-chrome
    # 通常の環境では、以下のイメージを使います。
    #image: selenium/standalone-chrome
    # M1 Mac など ARM で動作する環境では、以下のイメージを使います。
    #image: seleniarm/standalone-chromium
    image: ${DOCKER_SELENIUM_IMAGE_NAME}  # .envファイルに環境変数を定義する
    ports:
      # Selenium サーバに接続するポート
      - "11444:4444"
      # VNC で接続するポート
      - "11590:5900"
      # Selenium サーバのログを出力するポート
      - "11790:7900"
    # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"
    restart: unless-stopped

  # Web スクレイピングを実行するコンテナ
  scraping-app:
    container_name: rfctrans-python
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "11082:80"
    volumes:
      - ./main.py:/opt/app/main.py
      - ./src:/opt/app/src
      - ./tests:/opt/app/tests
      - ./templates:/opt/app/templates
      - ./data:/opt/app/data
      - ./html:/opt/app/html
      - ./scraping-app/.env:/opt/app/.env
    tty: true
    restart: unless-stopped

  # RFC翻訳結果を閲覧するためのWebページ
  nginx:
    container_name: rfctrans-nginx
    build: ./nginx
    ports:
      - "11080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped

  # Jenkinsコンテナ
  jenkins:
    container_name: rfctrans-jenkins
    image: jenkins/jenkins:lts
    ports:
      - "11081:8080"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    restart: unless-stopped
